from __future__ import annotations

from typing import Any


def chart_presentation() -> dict[str, Any]:
    return {
        "schema_version": 1,
        "kind": "strategy_trade_chart",
        "default_timeframe": "1m",
        "timeframes": ["1m", "5m"],
        "default_visible": ["tema9_5m", "tema20_5m", "macd_line_5m", "macd_signal_5m", "macd_hist_5m"],
        "indicators": [
            {
                "id": "tema9_5m",
                "source_column": "tema9_5m",
                "timeframe": "1m",
                "label": "TEMA 9 · 5m",
                "pane": "price",
                "style": "line",
                "color": "#0891b2",
                "line_width": 2,
            },
            {
                "id": "tema20_5m",
                "source_column": "tema20_5m",
                "timeframe": "1m",
                "label": "TEMA 20 · 5m",
                "pane": "price",
                "style": "line",
                "color": "#9333ea",
                "line_width": 2,
            },
            {
                "id": "macd_line_5m",
                "source_column": "macd_line_5m",
                "timeframe": "1m",
                "label": "MACD · 5m",
                "pane": "macd_5m",
                "style": "line",
                "color": "#2563eb",
                "line_width": 2,
            },
            {
                "id": "macd_signal_5m",
                "source_column": "macd_signal_5m",
                "timeframe": "1m",
                "label": "Signal · 5m",
                "pane": "macd_5m",
                "style": "line",
                "color": "#f97316",
                "line_width": 2,
            },
            {
                "id": "macd_hist_5m",
                "source_column": "macd_hist_5m",
                "timeframe": "1m",
                "label": "Histogram · 5m",
                "pane": "macd_5m",
                "style": "histogram",
                "color": "#64748b",
                "line_width": 2,
            },
            {
                "id": "tema9_5m",
                "source_column": "tema9",
                "timeframe": "5m",
                "label": "TEMA 9 · 5m",
                "pane": "price",
                "style": "line",
                "color": "#0891b2",
                "line_width": 2,
            },
            {
                "id": "tema20_5m",
                "source_column": "tema20",
                "timeframe": "5m",
                "label": "TEMA 20 · 5m",
                "pane": "price",
                "style": "line",
                "color": "#9333ea",
                "line_width": 2,
            },
            {
                "id": "macd_line_5m",
                "source_column": "macd_line",
                "timeframe": "5m",
                "label": "MACD · 5m",
                "pane": "macd_5m",
                "style": "line",
                "color": "#2563eb",
                "line_width": 2,
            },
            {
                "id": "macd_signal_5m",
                "source_column": "macd_signal",
                "timeframe": "5m",
                "label": "Signal · 5m",
                "pane": "macd_5m",
                "style": "line",
                "color": "#f97316",
                "line_width": 2,
            },
            {
                "id": "macd_hist_5m",
                "source_column": "macd_hist",
                "timeframe": "5m",
                "label": "Histogram · 5m",
                "pane": "macd_5m",
                "style": "histogram",
                "color": "#64748b",
                "line_width": 2,
            },
        ],
        "trade_annotations": {
            "entry_label": "quantity",
            "exit_label": "quantity",
            "show_entry_line": True,
            "show_exit_line": True,
            "show_stop_line": True,
            "show_trigger_line": True,
            "show_trade_region": True,
        },
    }
