import type { CanvasChartTimeframe } from "../../app/canvasWorkspace";
import type { ChartDisplayItem } from "../../app/components/ChartPanel";
import type { ChartsQuotesLayoutSettings } from "../../app/components/MarketMicrostructureContainers";
import type { MarketScannerSettings, ScannerSnapshotMeta, SignalStreamSettings, StrategyActivitySettings, WatchlistRuntimeResponse, WatchUniverseSettings } from "../../app/components/MarketScreenerContainers";
import type { WorkspaceWindowStatus } from "../../app/components/WorkspaceCanvas";
import type { TradingWorkspaceMode } from "../../app/tradingWorkspace";
import type { XbrlAnalysisSettings } from "../../app/components/XbrlAnalysisContainer";
import type { StrategyChartPresentation, StrategyDecisionEvent } from "../../app/strategyPresentation";
import type { CanvasReplayRun } from "../../app/replayRun";
export type HistoricalBar = { bar_end?: string; bar_start: string; close: number; high: number; is_closed?: boolean; last_event_ts?: string; low: number; open: number; volume: number };
export const EMPTY_STRATEGY_DECISIONS: StrategyDecisionEvent[] = [];
export type QmdStructureLevelCandidate = {
  level_id: number;
  confidence: number;
  created_at_ms: number;
  distance: number;
  evidence_score: number;
  hold_count: number;
  last_test_at_ms: number;
  lower: number;
  lifecycle: string;
  price: number;
  promotions: Array<{ timeframe: string; promoted_at_ms: number; score: number }>;
  footprint_session_date: string;
  footprint_as_of_ms: number;
  footprint: Array<{ offset_ticks: number; price: number; total_volume: number; buy_volume: number; sell_volume: number; neutral_volume: number; trade_count: number; largest_trade: number }>;
  total_volume: number;
  buy_volume: number;
  sell_volume: number;
  neutral_volume: number;
  trade_count: number;
  side: number;
  strength: number;
  touch_count: number;
  upper: number;
};
export type QmdStructureTimeframeState = {
  timeframe: string;
  direction: number;
  swing_high: number;
  swing_low: number;
  support?: Record<string, unknown>;
  resistance?: Record<string, unknown>;
  promoted_level_count: number;
};
export type QmdUnifiedStructureSource = {
  level_id: number;
  timeframe: string;
  side: number;
  price: number;
  pivot_at_ms: number;
  confirmed_at_ms: number;
  total_volume: number;
  buy_volume: number;
  sell_volume: number;
  neutral_volume: number;
  trade_count: number;
  source_kind: string;
  touch_count: number;
  hold_count: number;
  break_count: number;
  role_flip_count: number;
  last_test_at_ms: number;
};
export type QmdUnifiedStructureLevel = {
  unified_level_id: number;
  side: number;
  price: number;
  lower: number;
  upper: number;
  source_count: number;
  independent_pivot_count: number;
  timeframes: string[];
  created_at_ms: number;
  confirmed_at_ms: number;
  total_volume: number;
  buy_volume: number;
  sell_volume: number;
  neutral_volume: number;
  trade_count: number;
  pressure_bias: number;
  hold_probability: number;
  break_probability: number;
  touch_count: number;
  hold_count: number;
  break_count: number;
  role_flip_count: number;
  last_test_at_ms: number;
  lifecycle: "active" | "crossed" | "awaiting_retest" | "retest_contact" | "retired" | string;
  pending_side: number;
  sources: QmdUnifiedStructureSource[];
};
export type QmdUnifiedStructureLevelDelta = {
  upserts: QmdUnifiedStructureLevel[];
  removed: Array<{ unified_level_id: number; side: number }>;
};
export type HistoricalIndicator = {
  bar_start: string;
  qmd_structure_active_levels?: QmdStructureLevelCandidate[];
  qmd_structure_timeframe_states?: QmdStructureTimeframeState[];
  qmd_structure_unified_level_delta?: QmdUnifiedStructureLevelDelta;
  qmd_structure_unified_levels?: QmdUnifiedStructureLevel[];
} & Record<string, number | string | QmdStructureLevelCandidate[] | QmdStructureTimeframeState[] | QmdUnifiedStructureLevel[] | QmdUnifiedStructureLevelDelta | undefined>;
export type PreviewRow = Record<string, unknown>;
export type PnlCandleTimeframe = "30m" | "1h" | "1d" | "1M";
export type PnlCandle = {
  bucket_start: string;
  bucket_end: string;
  open: string | number;
  high: string | number;
  low: string | number;
  close: string | number;
  net_change: string | number;
  episode_count: number;
};
export type PerformanceJournalReport = {
  schema_version: number;
  episode_definition: string;
  summary: Record<string, string | number | null>;
  episodes: PreviewRow[];
  equity_curve: Array<{ time: string; value: string | number; drawdown: string | number }>;
  pnl_candles: Record<PnlCandleTimeframe, PnlCandle[]>;
  strategies: PreviewRow[];
  execution: Record<string, unknown> & { venues?: PreviewRow[] };
  risk: Record<string, string | number | null>;
  scope: Record<string, string | number | null>;
};
export type CanonicalTradingPreview = {
  schema_version: number;
  mode: string;
  provider: string;
  as_of: string;
  complete: boolean;
  stale: boolean;
  stale_reason: string;
  accounts: PreviewRow[];
  account_values: PreviewRow[];
  ledger: PreviewRow[];
  positions: PreviewRow[];
  position_lifecycles?: PreviewRow[];
  orders: PreviewRow[];
  executions: PreviewRow[];
  closed_trades: PreviewRow[];
  activity: PreviewRow[];
  strategy_activity?: PreviewRow[];
  strategy_activity_page?: { complete?: boolean; next_offset?: number | null };
  strategy_chart_activity?: PreviewRow[];
  closed_trades_note: string;
  performance_snapshot?: PerformanceSnapshot;
  performance_journal: PerformanceJournalReport;
  portfolio: {
    metrics: Record<string, string | number>;
    exposure: { long_value?: string | number; short_value?: string | number; net_value?: string | number; gross_value?: string | number; by_currency?: Record<string, string | number>; by_asset_class?: Record<string, string | number> };
    position_count: number;
    working_order_count: number;
    pending_commission_count: number;
    management?: {
      schema_version: number;
      complete: boolean;
      stale: boolean;
      stale_reason: string;
      accounts: Array<{
        account_key: string;
        account_id: string;
        account_class: string;
        mode: string;
        sync_state: string;
        control_mode: string;
        observed_at: string;
        stale_reason: string;
        policy: Record<string, unknown> & { identity?: string };
        available_policies: Array<Record<string, unknown> & { identity: string }>;
        strategy_allocations: Record<string, number>;
        disabled_strategy_allocations: string[];
        metrics: Record<string, string | number>;
        position_count: number;
        working_order_count: number;
        reservations: PreviewRow[];
        allocations: PreviewRow[];
        reconciliation: PreviewRow[];
        continuous_risk: PreviewRow;
        managed_order_groups: Array<{
          group_id: string;
          state: PreviewRow & {
            state?: string;
            current_limit_price?: number | null;
            protection_required_quantity?: number;
            protection_coverage_quantity?: number;
            intent?: PreviewRow & {
              ticker?: string;
              execution_policy?: PreviewRow;
              protection_profile?: PreviewRow;
            };
          };
        }>;
        pending_operational_commands: PreviewRow[];
      }>;
      groups: PreviewRow[];
      recent_decisions: PreviewRow[];
      operational_metrics?: {
        portfolio: {
          decision_count: number;
          disposition_counts: Record<string, number>;
          active_reservation_count: number;
          active_reserved_notional: number;
          reconciliation_issue_count: number;
          pending_command_count: number;
        };
        oms: {
          managed_group_count: number;
          outcome_unknown_count: number;
          unprotected_quantity: number;
          reconciliation_event_count: number;
          reconciliation_failure_count: number;
          last_reconciliation_at?: string | null;
        };
      };
    };
  };
};
export type PerformanceSnapshot = {
  schema_version?: number;
  as_of: string;
  session_date: string;
  net_pnl_today: string | number;
  open_position_count: number;
  unrealized_pnl: string | number;
  max_unrealized_pnl: string | number;
  max_unrealized_pnl_basis?: string;
  realized_pnl_today: string | number;
  available_cash: string | number;
  available_cash_basis: "available_funds" | "total_cash" | string;
  metrics?: PerformanceMetric[];
  source?: "performance_snapshot" | "canonical_state_v2";
};
export type PerformanceMetric = {
  id: string;
  label: string;
  value: string | number | null;
  format: "money" | "percent" | "ratio" | "count" | string;
  interpretation: "signed" | "favorable_high" | "adverse_high" | "neutral" | string;
  description: string;
  available: boolean;
};
export type LivePerformanceState = { data: PerformanceSnapshot | null; status: "loading" | "ready" | "stale" | "error" };
export type PerformanceSnapshotResponse = {
  as_of: string;
  complete: boolean;
  stale: boolean;
  stale_reason: string;
  performance_snapshot: PerformanceSnapshot;
};
export type CanvasPreview = {
  as_of: string;
  chart: { bars: HistoricalBar[]; indicators: HistoricalIndicator[]; symbol: string; timeframe: string };
  coverage: { event_count?: number; ticker_count?: number };
  errors: Record<string, string>;
  fills: PreviewRow[];
  journal: PreviewRow[];
  news: PreviewRow[];
  orders: PreviewRow[];
  portfolio: { account: PreviewRow; positions: PreviewRow[]; summary: PreviewRow };
  run?: CanvasReplayRun;
  scanner: PreviewRow[];
  scanner_meta?: ScannerSnapshotMeta;
  sec: PreviewRow[];
  strategy: {
    automatic: boolean;
    fixture?: boolean;
    revision: number;
    signals: PreviewRow[];
    decisions?: PreviewRow[];
    order_management?: PreviewRow[];
    run_id?: string;
    runtime_mode?: "backtest" | "backtest_debug" | "replay";
    state: string;
    strategy_id: string;
    name?: string;
    profile_id?: string;
    profile_revision?: number;
    deployment?: PreviewRow;
    action_definitions?: Array<{ action_id: string; category: string; description: string; kind: "intent" | "campaign_command"; name: string; runtime_action: string }>;
    action_policies?: Array<{ action_id: string; authority: string; description: string; name: string; policy_id: string }>;
    assignment?: PreviewRow | null;
    assignments?: PreviewRow[];
    definition?: { config?: { direction?: string; parameters?: Record<string, unknown>; parameter_space?: Record<string, unknown> }; name?: string };
    taxonomy?: { indicators?: PreviewRow[]; signals?: PreviewRow[]; presentation?: Partial<StrategyChartPresentation> };
  };
  trading: CanonicalTradingPreview;
  xbrl: PreviewRow[];
};

export type CanvasScannerSnapshot = {
  as_of: string;
  errors: Record<string, string>;
  meta: ScannerSnapshotMeta;
  rows: Record<string, unknown>[];
  signal_rows?: Record<string, unknown>[];
  watchlist_runtime?: WatchlistRuntimeResponse;
};
export type CanvasContext = { coverage: { event_count: number; session_date: string | null; ticker_count: number }; preview_time: string; session_date: string | null };
export type QmdLiveBar = HistoricalBar & { session_date?: string };
export type QmdLiveChartPayload = {
  bars: { current?: QmdLiveBar | null; history?: QmdLiveBar[] };
  errors?: Record<string, string>;
  indicators: { current?: HistoricalIndicator | null; history?: HistoricalIndicator[] };
  source?: string;
  stream_interval_ms?: number;
};
export type BarGptForecast = {
  prediction_id: string;
  model_id: string;
  model_version: "v2" | "v3";
  origin_us: number;
  available_at_us: number;
  forecast_kind: "physical" | "next_bar";
  horizon: string;
  timeframe: string;
  target_start_us: number;
  target_end_us: number;
  open: number;
  high: number;
  low: number;
  close: number;
  geometry_valid: boolean;
};
export type BarGptForecastPayload = { rows: BarGptForecast[]; row_count: number; ticker: string };
export type BarGptScopePayload = {
  status?: string;
  error?: string;
  ready_count?: number;
  ticker_count?: number;
  readiness?: Array<{
    ready: boolean;
    ticker: string;
    warm?: { status?: "queued" | "warming" | "ready" | "failed" | "cancelled"; error?: string };
  }>;
};
export type QmdBarHistory = {
  as_of: string;
  coverage_status?: "ready" | "stale" | "unavailable" | string;
  latest_session_date?: string | null;
  market_signal_events: QmdMarketSignalEvent[];
  earliest_session_date: string;
  has_more: boolean;
  has_more_in_session: boolean;
  history: QmdLiveBar[];
  indicators: HistoricalIndicator[];
  indicators_available: boolean;
  indicator_provenance?: QmdIndicatorProvenance;
  structure_events: QmdStructureEvent[];
  structure_level_history: QmdStructureLevelCandidate[];
  next_before: string;
  previous_session_before: string;
  stage?: "bars" | "full";
  split_adjustments?: Array<{
    effective_at: string;
    execution_date: string;
    source_inserted_at: string;
    split_from: number;
    split_to: number;
  }>;
  split_adjusted?: boolean;
  ticker: string;
  timeframe: string;
};
export type QmdIndicatorProvenance = {
  as_of?: string;
  complete?: boolean;
  calculation_revision?: string;
  corporate_action_revision?: string;
  engine_version?: string;
  indicator_schema_version?: number;
  source?: { source_plan_hash?: string; tiers?: string[] };
  stale_reason?: string;
  warm_up?: { recommended_minimum_bars?: number; returned_bars?: number; status?: string };
};
export type QmdMarketSignalEvent = {
  schema_version: number;
  signal_version: number;
  engine_version: string;
  event_id: string;
  signal_id: string;
  signal_key: string;
  producer: string;
  ticker: string;
  working_timeframe: string;
  confirmation_timeframe?: string | null;
  observed_at: string;
  effective_at: string;
  state: "triggered" | "updated" | "resolved" | "expired";
  direction: "bullish" | "bearish" | "neutral";
  score: number;
  rank_score: number;
  confidence: number;
  trigger_reason: string;
  resolution_reason?: string;
  reference_price: number;
  invalidation_price?: number | null;
};
export type QmdStructureEvent = {
  algorithm_version: number;
  event_id: number;
  sym: string;
  level_id?: number;
  timeframe: string;
  event_kind: string;
  direction: number;
  price: number;
  lower: number;
  upper: number;
  strength: number;
  confidence: number;
  lifecycle?: string;
  total_volume?: number;
  buy_volume?: number;
  sell_volume?: number;
  neutral_volume?: number;
  trade_count?: number;
  pivot_at: string;
  confirmed_at: string;
};
export type ChartHistoryCursor = {
  asOf: string;
  nextBefore: string;
  previousSessionBefore: string;
  sessionDate: string;
};
export type CanvasLiveChartState = {
  bars: QmdLiveBar[];
  canLoadEarlier: boolean;
  connected: boolean;
  marketSignalEvents: QmdMarketSignalEvent[];
  error: string;
  historyError: string;
  historyNotice: string;
  indicators: HistoricalIndicator[];
  indicatorsAvailable: boolean;
  indicatorProvenance?: QmdIndicatorProvenance;
  structureEvents: QmdStructureEvent[];
  structureLevelHistory: QmdStructureLevelCandidate[];
  lastUpdateAt: string;
  loadEarlier: () => void;
  loading: boolean;
  loadingEarlier: boolean;
  pointInTime: boolean;
  ready: boolean;
  splitAdjusted?: boolean;
};

export type BarGptChartVersion = "v2" | "v3";
export type BarGptChartQuantile = "q10" | "q50" | "q90";
export type CanvasChartSettings = {
  showSplitEvents: boolean;
  showVolume: boolean;
  symbol: string;
  timeframe: CanvasChartTimeframe;
  visibleIndicators: string[];
  barGptVersion: BarGptChartVersion;
  barGptQuantile: BarGptChartQuantile;
  barGptHorizon: "all" | "5s" | "30s" | "1m" | "5m" | "15m" | "1h";
  barGptTriggerMode: "auto" | "manual";
};
export type ContainerSettings = {
  version: 29;
  chart: CanvasChartSettings;
  charts_quotes: {
    daily: CanvasChartSettings;
    layout: ChartsQuotesLayoutSettings;
    main: CanvasChartSettings;
    month: CanvasChartSettings;
  };
  microstructure: { limit: number };
  fills: { limit: number; showCommission: boolean };
  positions: { limit: number; showPnl: boolean };
  closed_trades: { limit: number; showFees: boolean };
  activity: { limit: number };
  performance_journal: { limit: number; showRiskMultiple: boolean };
  news: { content: string; endDate: string; kind: string; limit: number; lookbackHours: number; rangeMode: "custom" | "preset"; startDate: string; ticker: string };
  ticker_news: { lookbackHours: number; showTeaser: boolean };
  news_detail: Record<string, never>;
  orders: { limit: number; showOrderIds: boolean };
  portfolio: { showExposure: boolean; showPnl: boolean };
  scanner: MarketScannerSettings;
  signal_stream: SignalStreamSettings;
  watchlist: WatchUniverseSettings;
  strategy_activity: StrategyActivitySettings;
  sec: { content: string; endDate: string; label: string; limit: number; lookbackHours: number; rangeMode: "custom" | "preset"; startDate: string; ticker: string };
  ticker_sec: { lookbackHours: number };
  sec_detail: Record<string, never>;
  strategy: { showSignals: boolean };
  xbrl: XbrlAnalysisSettings;
};

export type CanvasPreviewContext = { previewTime: string; sessionDate: string };
export type CanvasRuntimeMode = Extract<TradingWorkspaceMode, "backtest" | "backtest_debug" | "live" | "paper"> | "canvas" | "replay" | "research";
export type LinkedContainerState = { status: WorkspaceWindowStatus; symbol: string; title: string };
