"""Self-contained research chart; candle aggregation never recalculates zones."""
import json


def render(result,bars,profile):
    payload=json.dumps(dict(book=result,bars=bars,profile=profile),separators=(',',':')).replace('<','\\u003c')
    return HTML.replace('__DATA__',payload)


HTML=r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Historical session levels</title><style>
:root{color-scheme:light;--bg:#f7f9fc;--panel:#fff;--text:#172339;--muted:#59687b;--grid:#dfe6ef;--support:#12806c;--resistance:#c54350;--both:#7953b9;--accent:#275dcc;font:14px system-ui,sans-serif}
body.dark{color-scheme:dark;--bg:#101725;--panel:#172133;--text:#e5edf8;--muted:#a0b0c5;--grid:#2c3a50;--support:#4cc7aa;--resistance:#fc8290;--both:#ba9aff;--accent:#8cb6ff}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text)}header{padding:22px 26px 12px}h1{font-size:24px;margin:0 0 8px}p{margin:5px 0;color:var(--muted);line-height:1.5}.tools{display:flex;align-items:center;gap:12px;flex-wrap:wrap;padding:10px 26px}button,select{font:inherit;color:var(--text);background:var(--panel);border:1px solid var(--grid);border-radius:5px;padding:7px 12px;cursor:pointer}button:focus-visible,select:focus-visible{outline:2px solid var(--accent)}main{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:14px;padding:0 20px 20px}.plot,aside{background:var(--panel);border:1px solid var(--grid);border-radius:8px;overflow:hidden}.plot{position:relative}canvas{display:block;width:100%;height:660px;touch-action:none}aside{max-height:740px;overflow:auto}aside h2{font-size:16px;padding:16px;margin:0;border-bottom:1px solid var(--grid)}table{border-collapse:collapse;width:100%;font-size:13px}th,td{padding:10px 9px;text-align:right;border-bottom:1px solid var(--grid)}th:first-child,td:first-child{text-align:left}tbody tr{cursor:pointer}tbody tr:hover,tbody tr.selected{background:color-mix(in srgb,var(--accent) 12%,var(--panel))}.detail{padding:14px;line-height:1.6;color:var(--muted)}.legend{display:flex;gap:18px;flex-wrap:wrap;padding:12px 16px;color:var(--muted);font-size:12px}.dot{display:inline-block;width:9px;height:9px;margin-right:5px;border-radius:2px}.hint{padding:0 16px 12px;font-size:12px}#hover{min-height:26px;padding:0 16px;font-variant-numeric:tabular-nums;color:var(--muted)}footer{padding:0 26px 24px;color:var(--muted);font-size:12px;line-height:1.6}@media(max-width:1000px){main{grid-template-columns:1fr}aside{max-height:350px}canvas{height:520px}header,.tools{padding-left:20px}}@media(max-width:600px){canvas{height:420px}main{padding:0 8px 15px}h1{font-size:20px}}
</style><header><h1 id="heading"></h1><p id="summary"></p><p id="mode">Whole-session retrospective extraction · No prior levels · Available only after 20:00 ET</p></header>
<div class="tools"><label>Candles <select id="tf"><option value="1">1 second</option><option value="5">5 seconds</option><option value="30">30 seconds</option><option value="60" selected>1 minute</option><option value="300">5 minutes</option></select></label><button id="reset">Full session</button><label><input id="zones" type="checkbox" checked> Show levels</label><button id="theme">Dark theme</button><span id="window"></span></div>
<main><section class="plot"><div class="legend"><span><i class="dot" style="background:var(--support)"></i>Support reactions</span><span><i class="dot" style="background:var(--resistance)"></i>Resistance reactions</span><span><i class="dot" style="background:var(--muted)"></i>Awaiting retest (dashed)</span><span>Right: whole-session volume at price</span></div><canvas id="chart" aria-label="Historical candles and fixed extracted price bands"></canvas><div id="hover"></div><p class="hint">Wheel to zoom · Drag to pan · Double-click to reset · Select a level to inspect its evidence</p></section><aside><h2 id="levelTitle"></h2><table><thead><tr><th>Band / role</th><th>S</th><th>R</th><th>Cross</th></tr></thead><tbody id="levels"></tbody></table><div class="detail" id="detail">S / R: independent support / resistance rejections. Cross: accepted crossings. Counts describe the completed session, not predictions.</div></aside></main><footer id="provenance"></footer>
<script id="data" type="application/json">__DATA__</script><script>
const data=JSON.parse(document.querySelector('#data').textContent),book=data.book,raw=data.bars;
const canvas=document.querySelector('#chart'),ctx=canvas.getContext('2d'),fmt=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit',hour12:false});
const sessions=(book.sessions||[{session:book.session,start:book.source.start,end:book.source.end}]).map(s=>({...s,lo:Date.parse(s.start)/1000,hi:Date.parse(s.end)/1000}));let offset=sessions[0].lo;for(const s of sessions){s.offset=offset;offset+=s.hi-s.lo+1800}const axis=t=>{const s=sessions.find(s=>t>=s.lo&&t<=s.hi)||sessions[t<sessions[0].lo?0:sessions.length-1];return s.offset+t-s.lo};const clock=t=>{const s=sessions.find(s=>t>=s.offset&&t<=s.offset+s.hi-s.lo)||sessions.reduce((a,b)=>Math.abs(b.offset-t)<Math.abs(a.offset-t)?b:a);return s.lo+t-s.offset};const multi=sessions.length>1;const dateFmt=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',month:'2-digit',day:'2-digit'});const label=t=>(multi?dateFmt.format(clock(t)*1000)+' ':'')+fmt.format(clock(t)*1000);const begin=axis(sessions[0].lo),end=axis(sessions[sessions.length-1].hi);let left=begin,right=end,selected=null,drag=null,view=[];
window.levelIds=book.levels.map(x=>x.id);document.querySelector('#heading').textContent=book.ticker+' · '+book.session+' · Historical levels';
document.querySelector('#summary').textContent=book.counts.selected+' extracted zones · '+raw.length.toLocaleString()+' canonical seconds · 04:00–20:00 New York';
document.querySelector('#levelTitle').textContent='Level book ('+book.levels.length+')';
if(multi){document.querySelector('#mode').textContent='Finalized daily checkpoints | '+book.prior_level_count+' historical levels carried | Overnight/weekend gaps compressed | Each checkpoint available after its session close';document.querySelector('#summary').textContent=book.levels.length+' levels across '+sessions.length+' sessions | '+raw.length.toLocaleString()+' canonical seconds | 04:00-20:00 New York';document.querySelector('#reset').textContent='Both sessions';document.querySelector('#detail').textContent='Counts combine both completed sessions. Historical levels retain their identities; new levels begin during the second session. Select a row for matching, status and role history.';}
document.querySelector('#provenance').textContent=book.version+' · '+book.source.authority+' · '+book.source.clock+' · Input '+book.input_sha256+' | Band width '+(2*book.geometry.half_width).toFixed(2)+' USD; reaction distance '+book.geometry.prominence.toFixed(2)+' USD. '+(multi?'Thicker segments are carried historical levels; thinner segments originate in that session. ':'')+'Lines begin at first confirmed rejection; colors change with confirmed role evidence. Geometry is retrospective. Rejected candidates: '+book.counts.rejected+'. This is a research result, not a streaming checkpoint.';
const color=(role,css)=>css.getPropertyValue('--'+(role==='transition'?'muted':role)).trim();
const exactTime=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit',second:'2-digit',...(multi?{month:'2-digit',day:'2-digit'}:{}),hour12:false});
const detail=document.querySelector('#detail');detail.style.maxHeight='170px';detail.style.overflow='auto';document.querySelector('aside').insertBefore(detail,document.querySelector('table'));
for(const zone of [...book.levels].reverse()){const tr=document.createElement('tr');tr.dataset.id=zone.id;tr.innerHTML='<td>'+zone.lower.toFixed(2)+'–'+zone.upper.toFixed(2)+'<br><small>'+zone.evidence_role+(multi?' | '+(zone.historical?'historical':'new')+' '+zone.origin_session:'')+'</small></td><td>'+zone.support_rejections+'</td><td>'+zone.resistance_rejections+'</td><td>'+zone.accepted_crossings+'</td>';tr.tabIndex=0;const choose=()=>{selected=selected===zone.id?null:zone.id;document.querySelectorAll('tbody tr').forEach(r=>r.classList.toggle('selected',r.dataset.id===selected));document.querySelector('#detail').textContent=selected?'Zone '+zone.price.toFixed(2)+' · Final price side: '+zone.closing_role+(multi?' | Status: '+zone.strength_status+' | Matched today: '+zone.matched_today.length:'')+'. Volume in band: '+Math.round(zone.profile_volume).toLocaleString()+' shares. Proposals: '+zone.proposal_sources.join(', ')+'. Role timeline: '+zone.role_segments.map(e=>exactTime.format(e.start*1000)+'-'+exactTime.format(e.end*1000)+' '+(e.role==='transition'?'awaiting retest':e.role)).join('; '):'Select a zone to inspect its encounters.';draw()};tr.onclick=choose;tr.onkeydown=e=>{if(e.key==='Enter')choose()};document.querySelector('#levels').append(tr)}
function aggregate(){const step=Number(document.querySelector('#tf').value),m=new Map();for(const b of raw){const t=axis(Math.floor((b.t-1)/step)*step);let a=m.get(t);if(!a)m.set(t,{t,open:b.open,high:b.high,low:b.low,close:b.close,volume:b.volume});else{a.high=Math.max(a.high,b.high);a.low=Math.min(a.low,b.low);a.close=b.close;a.volume+=b.volume}}view=[...m.values()];draw()}
function draw(){const rect=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);const W=rect.width,H=rect.height,css=getComputedStyle(document.body),text=css.getPropertyValue('--muted'),grid=css.getPropertyValue('--grid');ctx.fillStyle=css.getPropertyValue('--panel');ctx.fillRect(0,0,W,H);const x0=18,x1=W-145,y0=20,y1=H-120;const visible=view.filter(b=>b.t>=left&&b.t<=right);if(!visible.length)return;let lo=Math.min(...visible.map(b=>b.low)),hi=Math.max(...visible.map(b=>b.high));const margin=Math.max((hi-lo)*.08,.03);lo-=margin;hi+=margin;const x=t=>x0+(t-left)/(right-left)*(x1-x0),y=p=>y1-(p-lo)/(hi-lo)*(y1-y0);window.chartGeometry={x0,x1,y0,y1};ctx.font='12px system-ui';ctx.lineWidth=1;if(multi){for(const session of sessions){const center=x(session.offset+(session.hi-session.lo)/2);ctx.fillStyle=text;ctx.fillText(session.session,Math.max(x0,Math.min(x1-90,center-40)),14);if(session.offset>begin){ctx.strokeStyle=grid;ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(x(session.offset-900),y0);ctx.lineTo(x(session.offset-900),H-30);ctx.stroke();ctx.setLineDash([])}}}
for(let i=0;i<=6;i++){const p=lo+(hi-lo)*i/6;ctx.strokeStyle=grid;ctx.beginPath();ctx.moveTo(x0,y(p));ctx.lineTo(x1,y(p));ctx.stroke();ctx.fillStyle=text;ctx.fillText(p.toFixed(2),x1+6,y(p)+4)}
const ticks=multi&&right-left>57600?sessions.flatMap((s,i)=>[0,14400,28800,43200,...(i===sessions.length-1?[57600]:[])].map(dt=>s.offset+dt)):Array.from({length:9},(_,i)=>left+(right-left)*i/8);for(const t of ticks){if(t<left||t>right||!sessions.some(s=>t>=s.offset&&t<=s.offset+s.hi-s.lo))continue;ctx.strokeStyle=grid;ctx.beginPath();ctx.moveTo(x(t),y0);ctx.lineTo(x(t),H-32);ctx.stroke();ctx.fillStyle=text;ctx.fillText(fmt.format(clock(t)*1000),Math.min(W-48,Math.max(0,x(t)-16)),H-12)}
ctx.save();ctx.beginPath();ctx.rect(x0,y0,x1-x0,y1-y0);ctx.clip();window.renderedSegments=[];if(document.querySelector('#zones').checked)for(const z of book.levels)for(const segment of z.role_segments){const a=Math.max(left,axis(segment.start)),b=Math.min(right,axis(segment.end));if(b<=a)continue;window.renderedSegments.push({id:z.id,start:clock(a),end:clock(b),role:segment.role,historical:!!segment.historical});ctx.globalAlpha=selected&&selected!==z.id?.04:.14;ctx.fillStyle=color(segment.role,css);ctx.fillRect(x(a),y(segment.upper??z.upper),x(b)-x(a),y(segment.lower??z.lower)-y(segment.upper??z.upper));ctx.globalAlpha=selected===z.id?1:.75;ctx.strokeStyle=color(segment.role,css);ctx.lineWidth=selected===z.id?3:(segment.historical?1.8:1);ctx.setLineDash(segment.role==='transition'?[5,4]:[]);ctx.beginPath();ctx.moveTo(x(a),y(segment.price??z.price));ctx.lineTo(x(b),y(segment.price??z.price));ctx.stroke();ctx.setLineDash([]);if(axis(segment.start)>=left){ctx.beginPath();ctx.arc(x(a),y(segment.price??z.price),selected===z.id?3:2,0,Math.PI*2);ctx.fill()}}ctx.globalAlpha=1;const step=Number(document.querySelector('#tf').value),bw=Math.max(1,Math.min(12,(x1-x0)*step/(right-left)*.7));for(const b of visible){const cx=x(b.t);ctx.strokeStyle=ctx.fillStyle=css.getPropertyValue(b.close>=b.open?'--support':'--resistance');ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(cx,y(b.high));ctx.lineTo(cx,y(b.low));ctx.stroke();ctx.fillRect(cx-bw/2,y(Math.max(b.open,b.close)),bw,Math.max(1,Math.abs(y(b.open)-y(b.close))))}ctx.restore();
const maxv=Math.max(...visible.map(b=>b.volume),1);for(const b of visible){ctx.globalAlpha=.55;ctx.fillStyle=css.getPropertyValue(b.close>=b.open?'--support':'--resistance');ctx.fillRect(x(b.t)-bw/2,H-35-b.volume/maxv*65,bw,b.volume/maxv*65)}ctx.globalAlpha=1;ctx.fillStyle=text;ctx.fillText('Volume (priced seconds)',x0,H-105);
const bins=new Map(),width=(hi-lo)/100;for(const p of data.profile){if(p.price<lo||p.price>hi)continue;const k=Math.floor((p.price-lo)/width);bins.set(k,(bins.get(k)||0)+p.volume)}const maxp=Math.max(...bins.values(),1);ctx.fillStyle=css.getPropertyValue('--accent');ctx.globalAlpha=.4;for(const [k,v] of bins){ctx.fillRect(x1+60,y(lo+(k+1)*width),v/maxp*75,Math.max(1,(y1-y0)/100-1))}ctx.globalAlpha=1;document.querySelector('#window').textContent=label(left)+' - '+label(right)+' ET';window.visibleLevelIds=document.querySelector('#zones').checked?book.levels.map(z=>z.id):[]}
function reset(){left=begin;right=end;draw()}function clamp(){const span=right-left;if(left<begin){left=begin;right=begin+span}if(right>end){right=end;left=end-span}}
canvas.addEventListener('wheel',e=>{e.preventDefault();const g=window.chartGeometry,f=Math.max(0,Math.min(1,(e.offsetX-g.x0)/(g.x1-g.x0))),anchor=left+f*(right-left),span=Math.max(60,Math.min(end-begin,(right-left)*Math.exp(e.deltaY*.002)));left=anchor-f*span;right=left+span;clamp();draw()},{passive:false});canvas.onpointerdown=e=>{drag={x:e.clientX,left,right};canvas.setPointerCapture(e.pointerId)};canvas.onpointerup=()=>drag=null;canvas.onpointermove=e=>{if(drag){const delta=(e.clientX-drag.x)/(window.chartGeometry.x1-window.chartGeometry.x0)*(drag.right-drag.left);left=drag.left-delta;right=drag.right-delta;clamp();draw()}else{const time=left+(e.offsetX-18)/(window.chartGeometry.x1-18)*(right-left);const b=view.reduce((a,b)=>Math.abs(b.t-time)<Math.abs(a.t-time)?b:a,view[0]);document.querySelector('#hover').textContent=label(b.t)+' ET · O '+b.open.toFixed(2)+' H '+b.high.toFixed(2)+' L '+b.low.toFixed(2)+' C '+b.close.toFixed(2)+' · '+Math.round(b.volume).toLocaleString()+' shares'}};canvas.ondblclick=reset;document.querySelector('#reset').onclick=reset;document.querySelector('#tf').onchange=aggregate;document.querySelector('#zones').onchange=draw;document.querySelector('#theme').onclick=()=>{document.body.classList.toggle('dark');document.querySelector('#theme').textContent=document.body.classList.contains('dark')?'Light theme':'Dark theme';draw()};new ResizeObserver(draw).observe(canvas);aggregate();
</script></html>'''
