from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol

from src.market_engine.events import MarketEvent
from src.trading_runtime.ibkr_schema import AccountLedger, AccountSummary, Execution, LiveOrder, OrderRequest, PortfolioPosition


class BrokerAdapter(Protocol):
    """The broker authority exposed to every runtime mode.

    Method shapes correspond to Client Portal account, order, trade, and
    portfolio resources. Implementations may transport them over HTTP (IBKR)
    or calculate them deterministically (simulation).
    """

    async def initialize(self) -> None: ...

    async def accounts(self) -> list[str]: ...

    async def preview_orders(self, account_id: str, orders: list[OrderRequest]) -> list[dict[str, Any]]: ...

    async def place_orders(self, account_id: str, orders: list[OrderRequest]) -> list[dict[str, Any]]: ...

    async def reply(self, reply_id: str, confirmed: bool) -> list[dict[str, Any]]: ...

    async def modify_order(self, account_id: str, order_id: str, order: OrderRequest) -> list[dict[str, Any]]: ...

    async def cancel_order(self, account_id: str, order_id: str) -> dict[str, Any]: ...

    async def live_orders(self) -> list[LiveOrder]: ...

    async def trades(self, days: int = 7) -> list[Execution]: ...

    async def positions(self, account_id: str) -> list[PortfolioPosition]: ...

    async def account_summary(self, account_id: str) -> AccountSummary: ...

    async def account_ledger(self, account_id: str) -> AccountLedger: ...

    async def on_market_event(self, event: MarketEvent) -> list[Execution]: ...

    async def expire_day_orders(self, account_id: str, at: datetime) -> list[LiveOrder]: ...
