import { useEffect, useState } from "react";
import { query } from "../../api/client";
import { researchApi as api } from "./researchApi";
import { ChartPanel, type ChartPayload } from "../../app/components/ChartPanel";
import type { UTCTimestamp } from "lightweight-charts";
import { EpisodeSecondAudit } from "./EpisodeSecondAudit";
import { researchBandColor } from "./researchChart";

type Decision = { listing_id:string; ticker:string; pair_id:number; selected:boolean; selection_reason:string; selection_score:number|null; best_score:number|null; score_threshold:number|null; allocation_ratio:number; group_id:number|null; time_us:number|null; start_us:number; reference_exit_us:number|null; entry_gain:number|null; close:number|null };
type Group = { group_id:number; start_us:number; end_us:number; duration_seconds:number; members:number; score_sum:number };
type Result = { config:{fee_per_share:number;threshold_mode:string;minimum_net_fee_multiple:number;minimum_return:number;grouping_seconds:number;maximum_group_seconds:number}; day:string; dataset_sha256:string; groups:Group[]; selected:number; rejected:number; pairs:number; source_rows:number; suppressed_entry_rows:number; filtered_rows:number; decisions:Decision[] };
type Chart = ChartPayload & { labels: {pair_id:number|null;time_us:number;action:string;action_1a:string;label_value:number;allocation_ratio:number;allocation_loss_mask:boolean;group_id:number|null}[] };
type Job = {job_id:string;status:string;stage:string;completed:number;total:number};
const clock=(us:number|null)=>us===null?"—":new Date(us/1000).toLocaleTimeString("en-GB",{timeZone:"America/New_York",hour12:false});
const num=(v:number|null)=>v===null?"—":v.toLocaleString(undefined,{maximumFractionDigits:6});

export function MarketTeacherPreview(){
 const [days,setDays]=useState<{day:string;role:string}[]>([]),[day,setDay]=useState("2026-07-31");
 const [fee,setFee]=useState(.005),[multiple,setMultiple]=useState(2),[cutoff,setCutoff]=useState(.001),[strength,setStrength]=useState(30),[span,setSpan]=useState(300);
 const [job,setJob]=useState<Job|null>(null),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(""),[selection,setSelection]=useState("all"),[group,setGroup]=useState(""),[search,setSearch]=useState(""),[offset,setOffset]=useState(0),[busy,setBusy]=useState(false);
 const [selected,setSelected]=useState<Decision|null>(null),[chart,setChart]=useState<Chart|null>(null),[show1a,setShow1a]=useState(false);
 useEffect(()=>{const abort=new AbortController();api<{days:{day:string;role:string}[]}>("/api/research/models/v6/saved-labels",{signal:abort.signal}).then(r=>setDays(r.days)).catch(e=>{if(!abort.signal.aborted)setError(String(e));});return()=>abort.abort();},[]);
 useEffect(()=>{if(!job||["complete","failed"].includes(job.status))return;const abort=new AbortController();const timer=window.setTimeout(()=>{api<Job>(`/api/research/models/v6/market-preview/status${query({job_id:job.job_id})}`,{signal:abort.signal}).then(setJob).catch(e=>{if(!abort.signal.aborted)setError(String(e));});},1500);return()=>{abort.abort();clearTimeout(timer);};},[job]);
 useEffect(()=>{if(job?.status!=="complete")return;const abort=new AbortController();api<Result>(`/api/research/models/v6/market-preview/result${query({job_id:job.job_id,group_id:group||undefined,search,offset,selection})}`,{signal:abort.signal,timeoutMs:300000}).then(setResult).catch(e=>{if(!abort.signal.aborted)setError(String(e));});return()=>abort.abort();},[job,group,search,offset,selection]);
 useEffect(()=>{if(!selected||!job)return;const abort=new AbortController();setChart(null);api<Chart>(`/api/research/models/v6/market-preview/chart${query({job_id:job.job_id,listing_id:selected.listing_id,start_us:selected.time_us??selected.start_us})}`,{signal:abort.signal,timeoutMs:300000}).then(setChart).catch(e=>{if(!abort.signal.aborted)setError(String(e));});return()=>abort.abort();},[selected,job?.job_id]);
 async function prepare(){setBusy(true);setError("");setResult(null);setSelected(null);setChart(null);setGroup("");setSelection("all");setOffset(0);try{setJob(await api<Job>("/api/research/models/v6/market-preview",{method:"POST",body:JSON.stringify({day,fee_per_share:fee,threshold_mode:"return",minimum_net_fee_multiple:multiple,minimum_return:cutoff,grouping_seconds:strength,maximum_group_seconds:span}),headers:{"Content-Type":"application/json"},timeoutMs:300000}));}catch(e){setError(String(e));}finally{setBusy(false);}}
 const payload=chart?{...chart,volume:chart.volume??[],overlay_series:chart.overlay_series??[],oscillator_series:chart.oscillator_series??[],regions:(chart.regions??[]).map(r=>({...r,color:researchBandColor(r.color)})),markers:chart.labels.filter(r=>r.action!=="CONTEXT" && r.pair_id===selected?.pair_id).map((r,i)=>{const action=show1a?r.action_1a:r.action;return {id:`1b-${i}`,time:(r.time_us/1e6-1) as UTCTimestamp,position:action==="EXIT"?"aboveBar" as const:"belowBar" as const,shape:action==="ENTRY"?"arrowUp" as const:action==="EXIT"?"arrowDown" as const:"circle" as const,size:.5,color:action==="ENTRY"?"var(--success)":action==="EXIT"?"var(--danger)":action==="HOLD"?"var(--info)":"var(--muted-foreground)",text:action==="ENTRY"&&!show1a?`${(r.allocation_ratio*100).toFixed(2)}% cash`:""};})}:null;
 return <div className="research-page research-market-preview"><header><h1>1b · Market selection & sizing preview</h1><p>Supervised targets only. 1a stays immutable. No training, cash simulation, publication or full-dataset extraction.</p></header>
 <section className="research-selection"><h2>1 · Score and filter</h2><div className="research-controls">
 <label>Session<select aria-label="1b session" value={day} onChange={e=>setDay(e.target.value)}>{days.map(d=><option key={d.day} value={d.day}>{d.day} · {d.role}</option>)}</select></label>
 <label>Fee / share / side<input aria-label="1b fee" type="number" min="0.0001" max="0.1" step="0.001" value={fee} onChange={e=>setFee(+e.target.value)}/></label>
 <label>Minimum score · %<input aria-label="1b return threshold" type="number" min="0" max="100" step="0.01" value={cutoff*100} onChange={e=>setCutoff(+e.target.value/100)}/></label><label>Minimum net fee multiple<input aria-label="1b fee multiple" type="number" min="0" max="100" value={multiple} onChange={e=>setMultiple(+e.target.value)}/></label></div>
 <p>score = (entry_gain − 2f) / (close + f). Both required: score ≥ minimum score and score &gt; m × 2f / (close + f). Gain is already time-discounted. One first qualifying 1a ENTRY per listing / S→L pair; later rows do not add allocation weight.</p>
 <h2>2 · Group and allocate</h2><div className="research-controls"><label>Grouping strength · seconds<input aria-label="1b grouping strength" type="number" min="1" max="600" value={strength} onChange={e=>setStrength(+e.target.value)}/></label><label>Maximum group span · seconds<input aria-label="1b maximum span" type="number" min="1" max="3600" value={span} onChange={e=>setSpan(+e.target.value)}/></label><button className="button primary" disabled={busy||job?.status==="running"||job?.status==="queued"} onClick={()=>void prepare()}>Prepare session preview</button></div>
 <p>Ordered, score-weighted time segmentation. Minimize within-group weighted time spread + median selected score × strength² per group. Equal timestamps stay together. Maximum span bounds the search; it is not a validated rule. Ratio = score / group score sum. $10,000 × ratio is illustrative, not a cash constraint.</p></section>
 {error&&<div className="canvas-inline-error" role="alert">{error}</div>}{job&&<p role="status">{job.status} · {job.stage} · {job.completed} / {job.total}</p>}
 {result&&<><p>Prepared settings: fee ${result.config.fee_per_share}/share/side · {(result.config.minimum_return*100).toFixed(3)}% score floor · {result.config.minimum_net_fee_multiple}× net fee threshold · grouping {result.config.grouping_seconds}s · maximum span {result.config.maximum_group_seconds}s</p><p><strong>{result.source_rows.toLocaleString()} 1a candle rows · {result.pairs.toLocaleString()} pairs · {result.selected.toLocaleString()} selected · {result.rejected.toLocaleString()} rejected · {result.groups.length.toLocaleString()} groups · {result.suppressed_entry_rows.toLocaleString()} ENTRY rows suppressed</strong></p><EpisodeSecondAudit jobId={job!.job_id} onInspect={r=>setSelected({...r,selection_score:r.score,best_score:r.score,score_threshold:result.config.minimum_return,start_us:r.time_us,reference_exit_us:null})}/><details><summary>Dataset and preview boundary</summary><p>{result.dataset_sha256} · {result.day}. Controls above are draft settings; this result uses the settings submitted to Prepare. Rejected pairs become WAIT with ratio 0. Only selected ENTRY rows supervise allocation; HOLD/EXIT sizing is masked. This objective measures temporal clustering, not session P&amp;L.</p></details>
 <div className="research-controls"><label>Group<select aria-label="1b group" value={group} onChange={e=>{setGroup(e.target.value);setOffset(0);}}><option value="">All groups / rejected pairs</option>{result.groups.map(g=><option key={g.group_id} value={g.group_id}>#{g.group_id} · {clock(g.start_us)}–{clock(g.end_us)} · {g.members} members · {g.duration_seconds}s</option>)}</select></label><label>Selection<select aria-label="1b selection" value={selection} onChange={e=>{setSelection(e.target.value);setOffset(0);}}><option value="all">All pairs</option><option value="selected">Selected</option><option value="rejected">Rejected</option></select></label><label>Find ticker<input aria-label="1b find ticker" value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);}}/></label><button className="button secondary compact" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-100))}>Previous rows</button><span>{result.filtered_rows ? offset+1 : 0}–{Math.min(offset+100,result.filtered_rows)} / {result.filtered_rows}</span><button className="button secondary compact" disabled={offset+100>=result.filtered_rows} onClick={()=>setOffset(offset+100)}>Next rows</button></div>
 <div className="research-preview-table"><table><thead><tr><th>Ticker / pair</th><th>Decision ET</th><th>Gain $/share</th><th>Score</th><th>Threshold</th><th>Selection</th><th>Group</th><th>Cash ratio</th><th>$10K equivalent</th></tr></thead><tbody>{result.decisions.map(d=><tr key={`${d.listing_id}:${d.pair_id}`} aria-selected={selected?.listing_id===d.listing_id&&selected?.pair_id===d.pair_id}><td><button className="research-ticker-button" onClick={()=>setSelected(d)}>{d.ticker} · {d.listing_id.split(":").at(-2)} / {d.pair_id}</button></td><td>{clock(d.time_us)}</td><td>{num(d.entry_gain)}</td><td>{num(d.selection_score??d.best_score)}</td><td>{num(d.score_threshold)}</td><td>{d.selection_reason}</td><td>{d.group_id??"—"}</td><td>{(d.allocation_ratio*100).toFixed(3)}%</td><td>${num(10000*d.allocation_ratio)}</td></tr>)}</tbody></table></div>
 <h2>3 · Inspect copied 1b labels</h2><p>Select a pair above. Rejected ENTRY/HOLD/EXIT become WAIT; context and unpaired WAIT rows stay unchanged.</p>
 {selected&&<><p>{selected.ticker} · pair {selected.pair_id} · {selected.selection_reason}</p><label className="research-preview-compare"><input type="checkbox" checked={show1a} onChange={e=>setShow1a(e.target.checked)}/>Show original 1a markers</label><p>Markers show the selected pair; nearby candles remain as context.</p>{payload?<><ChartPanel reference={selected.time_us == null ? undefined : {time:selected.time_us/1e6-1,startTime:selected.time_us/1e6-1,endTime:(selected.reference_exit_us??selected.time_us)/1e6-1}} ticker={selected.ticker} timeframe="1s" timeframes={["1s"]} payload={payload} loading={false} featureOptions={[]} indicatorOptions={[]} visibleColumns={["macd_line","macd_signal","macd_histogram","bar_vwap","session_vwap"]} visibleSupervisionGroups={[]} onTickerChange={()=>{}} onTimeframeChange={()=>{}} onVisibleColumnsChange={()=>{}} onVisibleSupervisionGroupsChange={()=>{}} tickerEditable={false} toolbarVariant="compact" showIndicatorControls={false} showSupervisionControls={false} baseHeight={460} persistedOnly settingsStorageKey="research.market-preview.chart.v1"/>
 <details><summary>Exact 1a → 1b candle targets</summary><table><thead><tr><th>Close ET</th><th>Pair</th><th>1a action</th><th>1b action</th><th>Group</th><th>Cash ratio</th><th>Sizing loss</th></tr></thead><tbody>{chart!.labels.map(r=><tr key={r.time_us} aria-selected={r.pair_id===selected.pair_id}><td>{clock(r.time_us)}</td><td>{r.pair_id??"Context"}</td><td>{r.action_1a}</td><td>{r.action}</td><td>{r.group_id??"—"}</td><td>{num(r.allocation_ratio)}</td><td>{r.allocation_loss_mask?"enabled":"masked"}</td></tr>)}</tbody></table></details></>:<p>Loading original and copied candle targets…</p>}</>}
 </>}
 </div>;
}
