use serde::Serialize;

/// Broad feature families reused from the earlier backtest/research regime.
///
/// The goal is to keep live, backtest, and offline research language aligned:
/// a scanner rule can ask for `volume_liquidity` or `market_structure` without
/// caring whether the feature came from streaming Rust state or a Polars batch.
#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum IndicatorCategory {
    Candles,
    Core,
    CrossTimeframe,
    Cycles,
    MarketStructure,
    Momentum,
    NbboLiquidity,
    Performance,
    PriceAction,
    ReferenceContext,
    Session,
    Shock,
    Statistics,
    TapeMicrostructure,
    TrendOverlap,
    Volatility,
    VolumeLiquidity,
}

/// Priority controls default runtime treatment.
///
/// P0 is live-decision infrastructure and should be available during trading.
/// P1 is useful enough to compute from closed bars by default.
/// P2 is strategy-specific and should be enabled deliberately.
/// P3 belongs in offline/on-demand Polars unless a strategy proves it needs it.
#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum IndicatorPriority {
    P0,
    P1,
    P2,
    P3,
}

/// Where the computation should normally happen.
#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ComputeMode {
    /// Update directly from every quote/trade event.
    RealtimeTick,
    /// Update when a timeframe bar closes.
    RealtimeBarClose,
    /// Keep in memory for decisions, but persist only selected decisions/signals.
    RealtimeInMemory,
    /// Compute from stored bars/quotes/trades with Polars when a view/model needs it.
    PolarsOnDemand,
    /// Load or refresh from reference/context sources, not from tick math.
    ReferenceLoad,
}

/// Persistence policy separates replay-critical data from derived convenience.
///
/// A field family promoted to durable persistence is treated as immutable for
/// schema-contract purposes. Do not remove it after production writes begin;
/// replace it with a new versioned field or table if the definition changes.
#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum PersistPolicy {
    /// Persist by default because the data is replay-critical or expensive to rebuild.
    Always,
    /// Persist only when a versioned signal contract explicitly depends on it.
    IfSignalUses,
    /// Keep in memory and write the values only with emitted/rejected signal decisions.
    SignalSnapshotOnly,
    /// Persist as a session/date reference snapshot, not as a tick/bar stream.
    ReferenceSnapshot,
    /// Do not persist by default; compute on demand in research/backtest code.
    NoDefault,
}

/// Implementation status lets the catalog be larger than today's code.
///
/// `Implemented` means qmd-gateway currently calculates this family or field.
/// `PlannedRealtime` means it is suitable for Rust streaming and should be a
/// normal next candidate.
/// `OfflineOnly` means it should stay out of the live hot path by default.
#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ImplementationStatus {
    Implemented,
    PlannedRealtime,
    StrategySpecific,
    OfflineOnly,
    ReferenceOnly,
}

/// One catalog row is intentionally a family, not always a single formula.
///
/// Families keep the catalog compact while still documenting all high-value
/// indicator sets. The `fields` list gives the concrete output names or the
/// accepted library family where the list is very large, such as TA-Lib candle
/// recognition functions.
#[derive(Clone, Copy, Debug, Serialize)]
pub struct IndicatorCatalogEntry {
    pub key: &'static str,
    pub label: &'static str,
    pub category: IndicatorCategory,
    pub priority: IndicatorPriority,
    pub compute_mode: ComputeMode,
    pub persist_policy: PersistPolicy,
    pub status: ImplementationStatus,
    pub inputs: &'static [&'static str],
    pub fields: &'static [&'static str],
    pub typical_timeframes: &'static [&'static str],
    pub storage_target: &'static str,
    pub rationale: &'static str,
}

pub fn indicator_catalog() -> &'static [IndicatorCatalogEntry] {
    INDICATOR_CATALOG
}

const ALL_LIVE_TFS: &[&str] = &["1s", "10s", "30s", "1m", "5m", "1h"];
const ENRICHED_QMD_TFS: &[&str] = &["100ms", "1s", "5s", "10s", "30s", "1m", "5m", "1h"];
const BAR_TFS: &[&str] = &["10s", "30s", "1m", "5m", "1h"];
const SHORT_TFS: &[&str] = &["1s", "10s", "30s", "1m"];
const SESSION_TFS: &[&str] = &["1m", "5m"];
const DAILY_TFS: &[&str] = &["1d"];
const NONE_TFS: &[&str] = &[];

const INDICATOR_CATALOG: &[IndicatorCatalogEntry] = &[
    IndicatorCatalogEntry {
        key: "core_bars",
        label: "Core OHLCV Bars",
        category: IndicatorCategory::Core,
        priority: IndicatorPriority::P0,
        compute_mode: ComputeMode::RealtimeTick,
        persist_policy: PersistPolicy::Always,
        status: ImplementationStatus::Implemented,
        inputs: &["trades", "quotes"],
        fields: &[
            "open",
            "high",
            "low",
            "close",
            "volume",
            "dollar_volume",
            "trade_count",
            "vwap",
            "price_change_pct",
            "high_low_range_pct",
        ],
        typical_timeframes: ALL_LIVE_TFS,
        storage_target: "memory_enriched_bars",
        rationale: "Base replay and chart state; every other bar-level feature depends on it.",
    },
    IndicatorCatalogEntry {
        key: "quote_mid_spread_bars",
        label: "Quote Midpoint And Spread Bars",
        category: IndicatorCategory::Core,
        priority: IndicatorPriority::P0,
        compute_mode: ComputeMode::RealtimeTick,
        persist_policy: PersistPolicy::Always,
        status: ImplementationStatus::Implemented,
        inputs: &["quotes"],
        fields: &[
            "bid_open",
            "bid_high",
            "bid_low",
            "bid_close",
            "ask_open",
            "ask_high",
            "ask_low",
            "ask_close",
            "mid_open",
            "mid_high",
            "mid_low",
            "mid_close",
            "spread_mean",
            "spread_bps_mean",
            "spread_bps_close",
        ],
        typical_timeframes: ALL_LIVE_TFS,
        storage_target: "memory_enriched_bars",
        rationale: "NBBO context is needed for slippage, liquidity filters, and honest tape-only trading decisions.",
    },
    IndicatorCatalogEntry {
        key: "session_context",
        label: "Session Context",
        category: IndicatorCategory::Session,
        priority: IndicatorPriority::P0,
        compute_mode: ComputeMode::RealtimeBarClose,
        persist_policy: PersistPolicy::IfSignalUses,
        status: ImplementationStatus::PlannedRealtime,
        inputs: &["bars", "session_clock", "previous_day_context"],
        fields: &[
            "minute_of_day",
            "session_phase",
            "session_elapsed_pct",
            "day_open",
            "day_high",
            "day_low",
            "distance_from_open_pct",
            "distance_from_day_high_pct",
            "distance_from_day_low_pct",
            "gap_from_previous_close_pct",
        ],
        typical_timeframes: SESSION_TFS,
        storage_target: "live_market_indicators_if_enabled,scanner_signal_snapshots",
        rationale: "Scanner rules need session awareness, but durable writes should happen only when a signal contract requires it.",
    },
    IndicatorCatalogEntry {
        key: "opening_range",
        label: "Opening Range And ORB State",
        category: IndicatorCategory::Session,
        priority: IndicatorPriority::P0,
        compute_mode: ComputeMode::RealtimeBarClose,
        persist_policy: PersistPolicy::IfSignalUses,
        status: ImplementationStatus::PlannedRealtime,
        inputs: &["bars", "session_clock"],
        fields: &[
            "opening_range_high",
            "opening_range_low",
            "opening_range_mid",
            "opening_range_volume",
            "opening_range_dollar_volume",
            "opening_range_breakout",
            "opening_range_reclaim",
            "opening_range_position_pct",
        ],
        typical_timeframes: SESSION_TFS,
        storage_target: "live_market_indicators",
        rationale: "High-value intraday setup family already used in older ORB strategies.",
    },
    IndicatorCatalogEntry {
        key: "tape_rates",
        label: "Tape And Quote Event Rates",
        category: IndicatorCategory::TapeMicrostructure,
        priority: IndicatorPriority::P0,
        compute_mode: ComputeMode::RealtimeTick,
        persist_policy: PersistPolicy::SignalSnapshotOnly,
        status: ImplementationStatus::Implemented,
        inputs: &["trades", "quotes"],
        fields: &[
            "trade_rate_10s",
            "trade_rate_60s",
            "quote_rate_10s",
            "quote_rate_60s",
            "trade_accel_10s_60s",
            "quote_accel_10s_60s",
        ],
        typical_timeframes: SHORT_TFS,
        storage_target: "live_memory,scanner_signal_snapshots",
        rationale: "Early movement often shows up as event-rate acceleration, but raw ticks and bar summaries are already durable.",
    },
    IndicatorCatalogEntry {
        key: "tape_pressure",
        label: "Tape Pressure And Imbalance",
        category: IndicatorCategory::TapeMicrostructure,
        priority: IndicatorPriority::P0,
        compute_mode: ComputeMode::RealtimeTick,
        persist_policy: PersistPolicy::SignalSnapshotOnly,
        status: ImplementationStatus::Implemented,
        inputs: &["trades", "quotes"],
        fields: &[
            "rolling_vwap_60s",
            "tape_imbalance_60s",
            "buy_pressure_60s",
            "sell_pressure_60s",
            "buy_volume",
            "sell_volume",
            "buy_sell_volume_delta",
            "cumulative_delta",
        ],
        typical_timeframes: SHORT_TFS,
        storage_target: "memory_enriched_bars,scanner_signal_snapshots",
        rationale: "Core order-flow proxy available from tape and NBBO; persist bar summaries and signal-time snapshots, not duplicate tick streams.",
    },
    IndicatorCatalogEntry {
        key: "microstructure_outlook",
        label: "Deterministic Microstructure Outlook",
        category: IndicatorCategory::TapeMicrostructure,
        priority: IndicatorPriority::P0,
        compute_mode: ComputeMode::RealtimeTick,
        persist_policy: PersistPolicy::IfSignalUses,
        status: ImplementationStatus::Implemented,
        inputs: &["quotes", "trades", "trade_aggregation_rules"],
        fields: &[
            "microstructure_fast_signal",
            "microstructure_fast_confidence",
            "microstructure_confirm_signal",
            "microstructure_confirm_confidence",
            "microstructure_context_signal",
            "microstructure_context_confidence",
            "microstructure_unified_signal",
            "microstructure_unified_confidence",
            "microstructure_unified_action",
            "microstructure_buy_trade_count",
            "microstructure_sell_trade_count",
            "microstructure_buy_volume",
            "microstructure_sell_volume",
            "microstructure_signed_volume_delta",
            "microstructure_cumulative_signed_volume_delta",
            "microstructure_anchored_flow_relationship",
            "microstructure_anchored_flow_relationship_score",
            "microstructure_transaction_imbalance",
            "microstructure_signed_volume_imbalance",
            "microstructure_level1_ofi_delta",
            "microstructure_cumulative_level1_ofi",
            "microstructure_level1_ofi",
            "microstructure_queue_imbalance",
            "microstructure_microprice_lean",
            "microstructure_midpoint_return_bps",
            "microstructure_trade_return_bps",
            "microstructure_aggressor_persistence",
            "microstructure_arrival_intensity_imbalance",
            "microstructure_arrival_rate_per_second",
            "microstructure_resiliency",
            "microstructure_aggressive_flow_score",
            "microstructure_displayed_liquidity_score",
            "microstructure_response_resiliency_score",
            "microstructure_regime_reliability",
        ],
        typical_timeframes: ENRICHED_QMD_TFS,
        storage_target: "memory_enriched_bars,live_market_indicators_if_enabled",
        rationale: "Merges 100 ms sufficient statistics into each requested timeframe, then derives one causal strategy signal plus inspectable order-flow, liquidity, response, and reliability diagnostics without averaging overlapping forecasts.",
    },
    IndicatorCatalogEntry {
        key: "large_trade_activity",
        label: "Large Trade Activity",
        category: IndicatorCategory::TapeMicrostructure,
        priority: IndicatorPriority::P0,
        compute_mode: ComputeMode::RealtimeTick,
        persist_policy: PersistPolicy::Always,
        status: ImplementationStatus::Implemented,
        inputs: &["trades"],
        fields: &[
            "avg_trade_size",
            "median_trade_size",
            "max_trade_size",
            "large_trade_count",
            "large_trade_volume",
            "large_trade_notional",
        ],
        typical_timeframes: ALL_LIVE_TFS,
        storage_target: "memory_enriched_bars",
        rationale: "Unusual size can separate real liquidity demand from quote noise.",
    },
    IndicatorCatalogEntry {
        key: "nbbo_liquidity",
        label: "NBBO Liquidity And Friction",
        category: IndicatorCategory::NbboLiquidity,
        priority: IndicatorPriority::P0,
        compute_mode: ComputeMode::RealtimeTick,
        persist_policy: PersistPolicy::SignalSnapshotOnly,
        status: ImplementationStatus::Implemented,
        inputs: &["quotes", "trades"],
        fields: &[
            "spread_bps",
            "spread_bps_mean",
            "quoted_bid_size_mean",
            "quoted_ask_size_mean",
            "quote_pressure",
            "depth_imbalance_proxy",
            "locked_crossed_quote_count",
            "effective_spread_mean",
            "slippage_proxy_bps",
            "liquidity_score",
        ],
        typical_timeframes: ALL_LIVE_TFS,
        storage_target: "memory_enriched_bars,scanner_signal_snapshots",
        rationale: "Filters bad fills and provides an NBBO substitute for L2; durable bars keep the history while signal snapshots keep decisions auditable.",
    },
    IndicatorCatalogEntry {
        key: "volume_relative",
        label: "Relative Volume And Dollar Volume",
        category: IndicatorCategory::VolumeLiquidity,
        priority: IndicatorPriority::P0,
        compute_mode: ComputeMode::RealtimeBarClose,
        persist_policy: PersistPolicy::IfSignalUses,
        status: ImplementationStatus::PlannedRealtime,
        inputs: &["bars", "daily_context"],
        fields: &[
            "rvol_1m",
            "rvol_5m",
            "relative_dollar_volume",
            "volume_sma_20",
            "volume_ema_20",
            "dollar_volume_sma_20",
            "volume_vs_avg_so_far",
            "volume_vs_recent_3",
        ],
        typical_timeframes: BAR_TFS,
        storage_target: "live_market_indicators",
        rationale: "High priority for scanner ranking and tradability checks.",
    },
    IndicatorCatalogEntry {
        key: "volume_classic",
        label: "Classic Volume Indicators",
        category: IndicatorCategory::VolumeLiquidity,
        priority: IndicatorPriority::P1,
        compute_mode: ComputeMode::RealtimeBarClose,
        persist_policy: PersistPolicy::IfSignalUses,
        status: ImplementationStatus::PlannedRealtime,
        inputs: &["bars"],
        fields: &["obv", "ad", "adosc", "cmf", "mfi", "pvt", "nvi", "pvi", "eom", "kvo", "force_index"],
        typical_timeframes: BAR_TFS,
        storage_target: "live_market_indicators",
        rationale: "Useful for divergence and confirmation, but not all variants need default persistence.",
    },
    IndicatorCatalogEntry {
        key: "momentum_core",
        label: "Core Momentum Oscillators",
        category: IndicatorCategory::Momentum,
        priority: IndicatorPriority::P1,
        compute_mode: ComputeMode::RealtimeBarClose,
        persist_policy: PersistPolicy::IfSignalUses,
        status: ImplementationStatus::Implemented,
        inputs: &["bars"],
        fields: &["rsi_14", "macd_line", "macd_signal", "macd_histogram", "return_1_bar", "price_vs_vwap_pct"],
        typical_timeframes: BAR_TFS,
        storage_target: "live_market_indicators",
        rationale: "Small set of high-signal indicators used by existing momentum-style strategies.",
    },
    IndicatorCatalogEntry {
        key: "momentum_extended",
        label: "Extended Momentum Oscillators",
        category: IndicatorCategory::Momentum,
        priority: IndicatorPriority::P2,
        compute_mode: ComputeMode::RealtimeBarClose,
        persist_policy: PersistPolicy::IfSignalUses,
        status: ImplementationStatus::StrategySpecific,
        inputs: &["bars"],
        fields: &[
            "roc",
            "rocp",
            "rocr",
            "mom",
            "stoch",
            "stochrsi",
            "cci",
            "cmo",
            "williams_r",
            "trix",
            "ppo",
            "apo",
            "awesome_oscillator",
            "kst",
            "tsi",
            "ultimate_oscillator",
        ],
        typical_timeframes: BAR_TFS,
        storage_target: "live_market_indicators_if_enabled",
        rationale: "Broad TA coverage, but many fields are redundant unless a strategy explicitly consumes them.",
    },
    IndicatorCatalogEntry {
        key: "trend_moving_averages",
        label: "Moving Averages And Trend Overlays",
        category: IndicatorCategory::TrendOverlap,
        priority: IndicatorPriority::P1,
        compute_mode: ComputeMode::RealtimeBarClose,
        persist_policy: PersistPolicy::IfSignalUses,
        status: ImplementationStatus::Implemented,
        inputs: &["bars"],
        fields: &[
            "sma",
            "ema_9",
            "ema_20",
            "ema_50",
            "wma",
            "dema",
            "tema",
            "hma",
            "kama",
            "zlema",
            "alma",
            "vwma",
            "t3",
            "ma_ribbon",
        ],
        typical_timeframes: BAR_TFS,
        storage_target: "live_market_indicators",
        rationale: "Trend regime and scanner confirmation are central to live momentum filters.",
    },
    IndicatorCatalogEntry {
        key: "trend_directional",
        label: "Directional Trend Indicators",
        category: IndicatorCategory::TrendOverlap,
        priority: IndicatorPriority::P1,
        compute_mode: ComputeMode::RealtimeBarClose,
        persist_policy: PersistPolicy::IfSignalUses,
        status: ImplementationStatus::PlannedRealtime,
        inputs: &["bars"],
        fields: &["adx", "plus_di", "minus_di", "plus_dm", "minus_dm", "supertrend", "psar", "ichimoku"],
        typical_timeframes: BAR_TFS,
        storage_target: "live_market_indicators_if_enabled",
        rationale: "Good for trend confirmation; persist only when part of a signal contract.",
    },
    IndicatorCatalogEntry {
        key: "volatility_core",
        label: "Core Volatility Indicators",
        category: IndicatorCategory::Volatility,
        priority: IndicatorPriority::P1,
        compute_mode: ComputeMode::RealtimeBarClose,
        persist_policy: PersistPolicy::IfSignalUses,
        status: ImplementationStatus::Implemented,
        inputs: &["bars"],
        fields: &[
            "true_range",
            "atr_14",
            "natr",
            "bollinger_mid_20",
            "bollinger_upper_20",
            "bollinger_lower_20",
            "bollinger_std_20",
            "realized_volatility",
        ],
        typical_timeframes: BAR_TFS,
        storage_target: "memory_enriched_bars,live_market_indicators",
        rationale: "Needed for risk, stop buffers, volatility filters, and breakout quality.",
    },
    IndicatorCatalogEntry {
        key: "volatility_extended",
        label: "Extended Volatility And Channels",
        category: IndicatorCategory::Volatility,
        priority: IndicatorPriority::P2,
        compute_mode: ComputeMode::RealtimeBarClose,
        persist_policy: PersistPolicy::IfSignalUses,
        status: ImplementationStatus::StrategySpecific,
        inputs: &["bars"],
        fields: &[
            "keltner_channel",
            "donchian_channel",
            "historical_volatility",
            "parkinson_volatility",
            "garman_klass_volatility",
            "yang_zhang_volatility",
            "rvi",
            "chop_index",
        ],
        typical_timeframes: BAR_TFS,
        storage_target: "live_market_indicators_if_enabled",
        rationale: "Useful for specialized strategies, but not required for every scanner row.",
    },
    IndicatorCatalogEntry {
        key: "price_action",
        label: "Price Action And Candle Shape",
        category: IndicatorCategory::PriceAction,
        priority: IndicatorPriority::P1,
        compute_mode: ComputeMode::RealtimeBarClose,
        persist_policy: PersistPolicy::IfSignalUses,
        status: ImplementationStatus::PlannedRealtime,
        inputs: &["bars"],
        fields: &[
            "body_pct",
            "upper_wick_pct",
            "lower_wick_pct",
            "close_location_value",
            "inside_bar",
            "outside_bar",
            "body_break",
            "range_expansion",
            "range_compression",
            "higher_high",
            "lower_low",
        ],
        typical_timeframes: BAR_TFS,
        storage_target: "live_market_indicators_if_enabled",
        rationale: "Reusable scanner state for breakouts, pullbacks, and exhaustion filters.",
    },
    IndicatorCatalogEntry {
        key: "qmd_generic_structure",
        label: "QMD Generic Market Structure",
        category: IndicatorCategory::MarketStructure,
        priority: IndicatorPriority::P0,
        compute_mode: ComputeMode::RealtimeTick,
        persist_policy: PersistPolicy::Always,
        status: ImplementationStatus::Implemented,
        inputs: &[
            "consolidated_nbbo",
            "eligible_trades",
            "completed_daily_bars",
            "estimated_luld",
        ],
        fields: &[
            "qmd_structure_direction",
            "qmd_structure_score",
            "qmd_structure_agreement",
            "qmd_structure_strength",
            "qmd_structure_confidence",
            "qmd_structure_support_field",
            "qmd_structure_resistance_field",
            "qmd_structure_pressure_bias",
            "qmd_structure_pressure_confidence",
            "qmd_structure_up_probability",
            "qmd_structure_support_price",
            "qmd_structure_support_lower",
            "qmd_structure_support_upper",
            "qmd_structure_resistance_price",
            "qmd_structure_resistance_lower",
            "qmd_structure_resistance_upper",
            "qmd_structure_active_levels",
            "qmd_structure_micro_direction",
            "qmd_structure_micro_swing_high",
            "qmd_structure_micro_swing_low",
            "qmd_structure_tactical_direction",
            "qmd_structure_tactical_swing_high",
            "qmd_structure_tactical_swing_low",
            "qmd_structure_context_direction",
            "qmd_structure_context_swing_high",
            "qmd_structure_context_swing_low",
            "qmd_structure_event_kind",
            "qmd_structure_event_scale",
            "qmd_structure_event_direction",
            "qmd_structure_event_price",
            "qmd_structure_event_pivot_at_ms",
            "qmd_structure_session_high",
            "qmd_structure_session_low",
            "qmd_structure_premarket_high",
            "qmd_structure_premarket_low",
            "qmd_structure_opening_range_high",
            "qmd_structure_opening_range_low",
            "qmd_structure_trade_volume_poc",
            "qmd_structure_nearest_round",
            "qmd_structure_luld_upper",
            "qmd_structure_luld_lower",
            "qmd_structure_52_week_high",
            "qmd_structure_52_week_low",
            "qmd_structure_prior_month_high",
            "qmd_structure_prior_month_low",
            "qmd_structure_prior_month_close",
        ],
        typical_timeframes: ENRICHED_QMD_TFS,
        storage_target:
            "qmd_structure_events_v1,qmd_structure_state_v1,live_market_indicators",
        rationale: "One causal event-native authority extracts micro, tactical, and context structure independently of chart candles, persists confirmed history and a full versioned restart checkpoint, and samples the same strategy-readable levels onto every enriched timeframe.",
    },
    IndicatorCatalogEntry {
        key: "shock_features",
        label: "Shock And Abnormality Features",
        category: IndicatorCategory::Shock,
        priority: IndicatorPriority::P0,
        compute_mode: ComputeMode::RealtimeBarClose,
        persist_policy: PersistPolicy::SignalSnapshotOnly,
        status: ImplementationStatus::PlannedRealtime,
        inputs: &["bars", "tick_indicators", "rolling_baselines"],
        fields: &[
            "return_zscore",
            "volume_zscore",
            "dollar_volume_zscore",
            "spread_zscore",
            "trade_rate_zscore",
            "quote_rate_zscore",
            "volatility_expansion",
            "gap_shock",
            "liquidity_dry_up",
            "price_volume_shock",
        ],
        typical_timeframes: SHORT_TFS,
        storage_target: "scanner_signal_snapshots,live_market_indicators_if_enabled",
        rationale: "High-priority scanner family for early unusual activity; store the decision context, not every transient z-score.",
    },
    IndicatorCatalogEntry {
        key: "cross_timeframe_confirmation",
        label: "Cross-Timeframe Confirmation",
        category: IndicatorCategory::CrossTimeframe,
        priority: IndicatorPriority::P2,
        compute_mode: ComputeMode::RealtimeInMemory,
        persist_policy: PersistPolicy::SignalSnapshotOnly,
        status: ImplementationStatus::StrategySpecific,
        inputs: &["bars", "indicators"],
        fields: &[
            "trend_alignment_1m_5m",
            "trend_alignment_5m_1h",
            "ema_stack_alignment",
            "lower_tf_accel_higher_tf_trend",
            "multi_tf_breakout_confirmed",
        ],
        typical_timeframes: &["1m", "5m", "1h"],
        storage_target: "scanner_signal_snapshots",
        rationale: "Important for decision quality, but best persisted as the final signal state rather than all intermediates.",
    },
    IndicatorCatalogEntry {
        key: "statistics",
        label: "Statistical Features",
        category: IndicatorCategory::Statistics,
        priority: IndicatorPriority::P3,
        compute_mode: ComputeMode::PolarsOnDemand,
        persist_policy: PersistPolicy::NoDefault,
        status: ImplementationStatus::OfflineOnly,
        inputs: &["bars", "indicator_history"],
        fields: &[
            "rolling_mean",
            "rolling_std",
            "rolling_skew",
            "rolling_kurtosis",
            "zscore",
            "correlation",
            "beta",
            "covariance",
            "entropy",
            "hurst",
            "autocorrelation",
            "linear_regression_forecast",
        ],
        typical_timeframes: BAR_TFS,
        storage_target: "polars_on_demand",
        rationale: "Large feature set is better generated vectorized for models/research than streamed for every ticker.",
    },
    IndicatorCatalogEntry {
        key: "cycles",
        label: "Cycle Indicators",
        category: IndicatorCategory::Cycles,
        priority: IndicatorPriority::P3,
        compute_mode: ComputeMode::PolarsOnDemand,
        persist_policy: PersistPolicy::NoDefault,
        status: ImplementationStatus::OfflineOnly,
        inputs: &["bars"],
        fields: &[
            "ht_trendline",
            "ht_dcperiod",
            "ht_dcphase",
            "ht_phasor",
            "ht_sine",
            "ht_trendmode",
        ],
        typical_timeframes: BAR_TFS,
        storage_target: "polars_on_demand",
        rationale: "Useful for experimentation, but too specialized for the live hot path by default.",
    },
    IndicatorCatalogEntry {
        key: "candlestick_patterns",
        label: "Candlestick Pattern Recognition",
        category: IndicatorCategory::Candles,
        priority: IndicatorPriority::P3,
        compute_mode: ComputeMode::PolarsOnDemand,
        persist_policy: PersistPolicy::NoDefault,
        status: ImplementationStatus::OfflineOnly,
        inputs: &["bars"],
        fields: &[
            "cdl_all_talib_patterns",
            "doji",
            "hammer",
            "engulfing",
            "harami",
            "morning_star",
            "evening_star",
            "shooting_star",
            "three_white_soldiers",
            "three_black_crows",
        ],
        typical_timeframes: BAR_TFS,
        storage_target: "polars_on_demand",
        rationale: "Very broad and often redundant; compute when researching pattern behavior, not by default live.",
    },
    IndicatorCatalogEntry {
        key: "performance",
        label: "Performance And Risk Metrics",
        category: IndicatorCategory::Performance,
        priority: IndicatorPriority::P3,
        compute_mode: ComputeMode::PolarsOnDemand,
        persist_policy: PersistPolicy::NoDefault,
        status: ImplementationStatus::OfflineOnly,
        inputs: &["orders", "fills", "portfolio", "bars"],
        fields: &[
            "log_return",
            "cumulative_return",
            "drawdown",
            "sharpe",
            "sortino",
            "realized_pnl",
            "unrealized_pnl",
            "exposure",
        ],
        typical_timeframes: NONE_TFS,
        storage_target: "portfolio_reports_or_polars_on_demand",
        rationale: "Portfolio evaluation belongs to broker/backtest portfolio state and reporting, not per-tick indicator state.",
    },
    IndicatorCatalogEntry {
        key: "reference_context",
        label: "Reference And Fundamental Context",
        category: IndicatorCategory::ReferenceContext,
        priority: IndicatorPriority::P0,
        compute_mode: ComputeMode::ReferenceLoad,
        persist_policy: PersistPolicy::ReferenceSnapshot,
        status: ImplementationStatus::ReferenceOnly,
        inputs: &["clickhouse_reference", "massive_rest", "broker_reference"],
        fields: &[
            "ibkr_conid",
            "float_bucket",
            "short_pressure_label",
            "short_squeeze_likelihood",
            "market_cap_bucket",
            "sector",
            "industry",
            "news_flag",
            "ssr_flag",
            "halt_flag",
        ],
        typical_timeframes: DAILY_TFS,
        storage_target: "session_reference_snapshot",
        rationale: "Not a streaming formula, but critical scanner context and order-routing metadata.",
    },
];
